// ============================================================================
// cie33-safety-review
// ----------------------------------------------------------------------------
// Clinician review workflow for CIE 3.3 intakes held by the safety sentinel.
//
// Authority model:
//  - The caller's identity comes from the verified JWT only.
//  - Access requires an ACTIVE, NON-REVOKED, UNEXPIRED, PATIENT-SCOPED grant in
//    clinician_patient_authorizations. Admin role and view-as sessions confer
//    nothing here, and the grant is rechecked inside the write transaction.
//  - A clinician cannot review their own intake, cannot answer the safety
//    question on the patient's behalf, and patients cannot self-clear a hold.
//
// A disposition of "permit_resumption" is PERMISSION TO RESUME INTAKE. It is
// not a determination that risk is absent, not treatment approval, and no
// contact, diagnosis or prescription is generated by this function.
// ============================================================================
import { authenticateRequest, jsonResponse } from "../_shared/auth.ts";
import { permitResumption, IntakeError } from "../_shared/cie33/engine.ts";
import type { IntakeState, IntakeEntry } from "../_shared/cie33/engine.ts";
import { contentHash } from "../_shared/cie33/reference/canonical.ts";

const cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};
const uuid =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

interface ActiveGrant {
  id: string;
  patient_user_id: string;
  expires_at: string;
}

function latestSafety(state: IntakeState): IntakeEntry | undefined {
  return [...(state.entries ?? [])]
    .filter((e) => e.key === "safety")
    .at(-1);
}

function answerText(entry: IntakeEntry | undefined): string | null {
  const response = entry?.answer?.semanticResponse;
  if (!response) return entry?.answer?.missingness?.kind ?? null;
  if (response.kind === "boolean") return response.value ? "Yes" : "No";
  if (response.kind === "short_text") return response.text;
  if (response.kind === "single_select") return response.optionId;
  return null;
}

function safetyDetail(state: IntakeState) {
  const entries = (state.entries ?? []).filter((e) => e.key === "safety");
  return entries.map((e) => ({
    witness_id: e.witness.id,
    prompt: e.question.promptRendered,
    window: e.question.temporal?.range?.anchorText ?? null,
    answer: answerText(e),
    submitted_at: e.answer.acceptedAt,
    supersedes: e.supersedes ?? null,
  }));
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: cors });
  if (req.method !== "POST")
    return jsonResponse({ error: "method_not_allowed" }, 405, cors);

  const result = await authenticateRequest(req);
  if (!result.ok)
    return jsonResponse(result.error.body, result.error.status, cors);
  const clinician = result.auth.callerUserId;
  const db = result.auth.serviceClient;

  let body: Record<string, unknown>;
  try {
    body = await req.json();
  } catch {
    return jsonResponse({ error: "invalid_json" }, 400, cors);
  }

  const nowIso = new Date().toISOString();
  const { data: grantRows, error: grantError } = await db
    .from("clinician_patient_authorizations")
    .select("id, patient_user_id, expires_at")
    .eq("clinician_user_id", clinician)
    .is("revoked_at", null)
    .gt("expires_at", nowIso);
  if (grantError) {
    console.error("cie33-safety-review authority lookup failed");
    return jsonResponse({ error: "review_unavailable" }, 500, cors);
  }
  const grants = (grantRows ?? []).filter(
    (g) => g.patient_user_id !== clinician,
  ) as ActiveGrant[];
  const grantFor = (patient: string) =>
    grants.find((g) => g.patient_user_id === patient);

  if (grants.length === 0)
    return jsonResponse(
      {
        error: "not_authorized",
        message:
          "You do not hold an active review authorization for any patient. An administrator must authorize you for a specific patient.",
        authorized_patients: 0,
      },
      403,
      cors,
    );

  try {
    if (body.action === "queue") {
      const patientIds = grants.map((g) => g.patient_user_id);
      const { data: sessions, error } = await db
        .from("cie33_sessions")
        .select("id, user_id, revision, state, updated_at")
        .in("user_id", patientIds)
        .order("updated_at", { ascending: false });
      if (error) throw error;
      const { data: profiles } = await db
        .from("profiles")
        .select("user_id, display_name")
        .in("user_id", patientIds);
      const names = new Map(
        (profiles ?? []).map((p) => [p.user_id, p.display_name]),
      );
      const held = (sessions ?? []).filter((row) => {
        const state = row.state as IntakeState;
        return (
          state?.safety === "handoff_required" ||
          state?.safety === "recheck_required"
        );
      });
      return jsonResponse(
        {
          authorized_patients: patientIds.length,
          sessions: held.map((row) => {
            const state = row.state as IntakeState;
            const safety = latestSafety(state);
            const grant = grantFor(row.user_id)!;
            return {
              session_id: row.id,
              patient_user_id: row.user_id,
              patient_name: names.get(row.user_id) ?? null,
              revision: row.revision,
              state_hash: state.stateHash,
              phase: state.phase,
              safety: state.safety,
              authorization_expires_at: grant.expires_at,
              safety_witness_id: safety?.witness.id ?? null,
              safety_prompt: safety?.question.promptRendered ?? null,
              safety_answer: answerText(safety),
              safety_answered_at: safety?.answer.acceptedAt ?? null,
              updated_at: row.updated_at,
            };
          }),
        },
        200,
        cors,
      );
    }

    if (body.action === "detail") {
      const sessionId = String(body.session_id ?? "");
      if (!uuid.test(sessionId))
        return jsonResponse({ error: "invalid_request" }, 400, cors);
      const { data: row, error } = await db
        .from("cie33_sessions")
        .select("id, user_id, revision, state, updated_at")
        .eq("id", sessionId)
        .maybeSingle();
      if (error) throw error;
      if (!row || !grantFor(row.user_id))
        return jsonResponse(
          {
            error: "not_authorized",
            message: "You are not authorized to review this intake.",
          },
          403,
          cors,
        );
      const state = row.state as IntakeState;
      const { data: reviews } = await db
        .from("cie33_safety_reviews")
        .select(
          "id, clinician_user_id, disposition, encounter_at, rationale, assessment_note, patient_instructions, source_revision, source_witness_id, result_revision, created_at",
        )
        .eq("session_id", sessionId)
        .order("created_at", { ascending: true });
      return jsonResponse(
        {
          session: {
            session_id: row.id,
            patient_user_id: row.user_id,
            revision: row.revision,
            state_hash: state.stateHash,
            phase: state.phase,
            safety: state.safety,
            started_at: state.startedAt,
            updated_at: row.updated_at,
            answered_count: state.entries?.length ?? 0,
            safety_history: safetyDetail(state),
            safety_review: state.safetyReview ?? null,
          },
          reviews: reviews ?? [],
        },
        200,
        cors,
      );
    }

    if (body.action === "submit") {
      const requestId = String(body.request_id ?? "");
      const sessionId = String(body.session_id ?? "");
      const patient = String(body.patient_user_id ?? "");
      const disposition = String(body.disposition ?? "");
      const encounterAt = String(body.encounter_at ?? "");
      const assessmentNote = String(body.assessment_note ?? "").trim();
      const rationale = String(body.rationale ?? "").trim();
      const instructions = String(body.patient_instructions ?? "").trim();
      const sourceWitnessId = String(body.source_witness_id ?? "");
      const expectedRevision = body.expected_revision;
      const expectedHash = String(body.expected_hash ?? "");

      if (!uuid.test(requestId))
        return jsonResponse(
          {
            error: "request_id_required",
            message: "A valid request ID is required.",
          },
          400,
          cors,
        );
      if (!uuid.test(sessionId) || !uuid.test(patient))
        return jsonResponse({ error: "invalid_request" }, 400, cors);
      if (patient === clinician)
        return jsonResponse(
          {
            error: "self_review_forbidden",
            message: "A clinician cannot review their own intake.",
          },
          403,
          cors,
        );
      if (!grantFor(patient))
        return jsonResponse(
          {
            error: "not_authorized",
            message:
              "Your authorization for this patient is missing, expired or revoked.",
          },
          403,
          cors,
        );
      if (!["keep_hold", "permit_resumption"].includes(disposition))
        return jsonResponse(
          { error: "invalid_disposition" },
          400,
          cors,
        );
      if (!Number.isInteger(expectedRevision) || !expectedHash.startsWith("sha256:"))
        return jsonResponse(
          {
            error: "state_binding_required",
            message: "Reload the held intake before recording a disposition.",
          },
          409,
          cors,
        );
      if (!encounterAt || Number.isNaN(Date.parse(encounterAt)))
        return jsonResponse(
          {
            error: "encounter_time_required",
            message: "Record when you assessed or contacted this patient.",
          },
          400,
          cors,
        );
      if (Date.parse(encounterAt) > Date.now() + 60000)
        return jsonResponse(
          {
            error: "encounter_time_invalid",
            message: "The encounter time cannot be in the future.",
          },
          400,
          cors,
        );
      if (assessmentNote.length < 20 || rationale.length < 20)
        return jsonResponse(
          {
            error: "documentation_required",
            message:
              "Document the assessment and your rationale (at least 20 characters each).",
          },
          400,
          cors,
        );
      if (instructions.length < 10)
        return jsonResponse(
          {
            error: "instructions_required",
            message: "Record the follow-up instructions for this patient.",
          },
          400,
          cors,
        );

      // A retry of a request that already succeeded must return what was
      // recorded, not a conflict. The intake has moved on by then, so this
      // replay check has to run before the compare-and-set below.
      const { data: recorded } = await db
        .from("cie33_safety_reviews")
        .select("id, disposition, session_id, patient_user_id")
        .eq("clinician_user_id", clinician)
        .eq("request_id", requestId)
        .maybeSingle();
      if (recorded) {
        if (
          recorded.session_id !== sessionId ||
          recorded.patient_user_id !== patient
        )
          return jsonResponse(
            {
              error: "idempotency_conflict",
              message:
                "This request ID was already used for a different review.",
            },
            409,
            cors,
          );
        return jsonResponse(
          {
            review: { review_id: recorded.id, replayed: true },
            disposition: recorded.disposition,
            note: "This disposition was already recorded. Nothing was changed.",
          },
          200,
          cors,
        );
      }

      const { data: row, error } = await db
        .from("cie33_sessions")
        .select("id, user_id, revision, state")
        .eq("id", sessionId)
        .eq("user_id", patient)
        .maybeSingle();
      if (error) throw error;
      if (!row)
        return jsonResponse(
          { error: "session_not_found", message: "Intake not found." },
          404,
          cors,
        );
      const current = row.state as IntakeState;
      if (
        row.revision !== expectedRevision ||
        current.stateHash !== expectedHash
      )
        return jsonResponse(
          {
            error: "stale_state",
            message:
              "This intake changed since you loaded it. Reload the held intake and review the current state.",
          },
          409,
          cors,
        );
      if (current.safety !== "handoff_required")
        return jsonResponse(
          {
            error: "not_held",
            message: "This intake is not currently on a safety hold.",
          },
          409,
          cors,
        );

      const held = latestSafety(current);
      if (!held || held.witness.id !== sourceWitnessId)
        return jsonResponse(
          {
            error: "safety_witness_mismatch",
            message: "Reload the held intake before recording a disposition.",
          },
          409,
          cors,
        );

      const requestHash = contentHash({
        clinician,
        patient,
        sessionId,
        requestId,
        disposition,
        encounterAt,
        assessmentNote,
        rationale,
        instructions,
        sourceWitnessId,
        expectedRevision,
        expectedHash,
      });

      let nextState: IntakeState | null = null;
      if (disposition === "permit_resumption") {
        const grant = grantFor(patient)!;
        nextState = permitResumption(
          current,
          {
            // The review row id is assigned in-transaction; the state pointer
            // binds the clinician, their authorization and the original witness.
            reviewId: requestId,
            authorizationId: grant.id,
            clinicianUserId: clinician,
            sourceWitnessId,
          },
          nowIso,
        );
      }

      const { data: rpcData, error: rpcError } = await db.rpc(
        "cie33_submit_safety_review",
        {
          p_clinician: clinician,
          p_patient: patient,
          p_request_id: requestId,
          p_request_hash: requestHash,
          p_session_id: sessionId,
          p_expected_revision: expectedRevision,
          p_expected_hash: expectedHash,
          p_disposition: disposition,
          p_encounter_at: new Date(encounterAt).toISOString(),
          p_assessment_note: assessmentNote,
          p_rationale: rationale,
          p_patient_instructions: instructions,
          p_source_witness_id: sourceWitnessId,
          p_state: nextState,
        },
      );
      if (rpcError) {
        const message = rpcError.message ?? "";
        if (message.includes("IDEMPOTENCY_CONFLICT") || rpcError.code === "23505")
          return jsonResponse(
            {
              error: "idempotency_conflict",
              message:
                "This request ID was already used for a different review.",
            },
            409,
            cors,
          );
        if (message.includes("STALE_STATE") || rpcError.code === "40001")
          return jsonResponse(
            {
              error: "stale_state",
              message:
                "This intake changed while you were writing. Reload and review the current state.",
            },
            409,
            cors,
          );
        if (
          message.includes("NOT_AUTHORIZED") ||
          message.includes("SELF_REVIEW_FORBIDDEN")
        )
          return jsonResponse(
            {
              error: "not_authorized",
              message:
                "Your authorization for this patient is missing, expired or revoked.",
            },
            403,
            cors,
          );
        if (message.includes("NOT_HELD"))
          return jsonResponse(
            {
              error: "not_held",
              message: "This intake is not currently on a safety hold.",
            },
            409,
            cors,
          );
        if (message.includes("SESSION_NOT_FOUND"))
          return jsonResponse({ error: "session_not_found" }, 404, cors);
        if (message.includes("INVALID_PERMIT"))
          return jsonResponse(
            {
              error: "invalid_permit",
              message: "The resumption state could not be verified. Reload.",
            },
            409,
            cors,
          );
        throw rpcError;
      }

      return jsonResponse(
        {
          review: rpcData,
          disposition,
          note:
            disposition === "permit_resumption"
              ? "Recorded as permission to resume intake. A fresh safety question has been issued to the patient; the original answer is retained."
              : "Recorded. The safety hold remains in place.",
        },
        200,
        cors,
      );
    }

    return jsonResponse({ error: "unknown_action" }, 400, cors);
  } catch (error) {
    if (error instanceof IntakeError)
      return jsonResponse(
        { error: error.code.toLowerCase(), message: error.message },
        error.status,
        cors,
      );
    console.error("cie33-safety-review failed", {
      code: (error as { code?: string })?.code ?? "internal",
    });
    return jsonResponse(
      {
        error: "review_unavailable",
        message:
          "The review could not be completed. No change was recorded. Retry.",
      },
      500,
      cors,
    );
  }
});
