delete from public.celf_feature_map where map_version = 'celf-v0.4';

insert into public.celf_feature_map (source_system, reveal_canonical, celf_feature_name, celf_feature_label, celf_domain, celf_panel_group, unit_canonical, map_version)
select source_system, reveal_canonical, celf_feature_name, celf_feature_label, celf_domain, celf_panel_group, unit_canonical, 'celf-v0.4'
from public.celf_feature_map
where map_version = 'celf-v0.3';

insert into public.celf_feature_map (source_system, reveal_canonical, celf_feature_name, celf_feature_label, celf_domain, celf_panel_group, unit_canonical, map_version) values
('fibroscan','SWS','fibroscan_sws','Shear Wave Speed','liver','FibroScan','m/s','celf-v0.4'),
('fibroscan','Shear Wave Speed','fibroscan_sws','Shear Wave Speed','liver','FibroScan','m/s','celf-v0.4'),
('fibroscan','SWS (m/s)','fibroscan_sws','Shear Wave Speed','liver','FibroScan','m/s','celf-v0.4'),
('fibroscan','CAP (dB/m)','fibroscan_cap','Controlled Attenuation Parameter (steatosis)','liver','FibroScan','dB/m','celf-v0.4'),
('fibroscan','E (kPa)','fibroscan_lsm','Liver Stiffness Measurement','liver','FibroScan','kPa','celf-v0.4'),
('fibroscan','E(kPa)','fibroscan_lsm','Liver Stiffness Measurement','liver','FibroScan','kPa','celf-v0.4'),
('lab','Prolactin','hormone_prolactin','Prolactin','hormones','Hormone Panel','ng/mL','celf-v0.4'),
('lab','PROLACTIN, SERUM','hormone_prolactin','Prolactin','hormones','Hormone Panel','ng/mL','celf-v0.4'),
('lab','Zinc','minerals_zinc','Zinc','minerals','Mineral Panel','mcg/dL','celf-v0.4'),
('lab','ZINC, SERUM','minerals_zinc','Zinc','minerals','Mineral Panel','mcg/dL','celf-v0.4'),
('lab','Testosterone, Free','hormone_testosterone_free','Free Testosterone','hormones','Hormone Panel','pg/mL','celf-v0.4'),
('lab','Free Testosterone','hormone_testosterone_free','Free Testosterone','hormones','Hormone Panel','pg/mL','celf-v0.4'),
('lab','FREE TESTOSTERONE','hormone_testosterone_free','Free Testosterone','hormones','Hormone Panel','pg/mL','celf-v0.4'),
('lab','Hemoglobin','cbc_hemoglobin','Hemoglobin','hematology','CBC','g/dL','celf-v0.4'),
('lab','Platelet Count','cbc_platelets','Platelets','hematology','CBC','10^3/uL','celf-v0.4'),
('lab','RBC Count','cbc_rbc','Red Blood Cell Count','hematology','CBC','10^6/uL','celf-v0.4'),
('lab','WBC Count','cbc_wbc','White Blood Cell Count','hematology','CBC','10^3/uL','celf-v0.4'),
('lab','Creatinine, Serum','renal_creatinine','Creatinine','renal','CMP','mg/dL','celf-v0.4'),
('lab','Urea','renal_bun','Blood Urea Nitrogen','renal','CMP','mg/dL','celf-v0.4'),
('lab','Uric Acid, Serum','metabolic_uric_acid','Uric Acid','metabolic','CMP Extended','mg/dL','celf-v0.4'),
('lab','Glucose, Fasting','glucose_fasting','Fasting Glucose','glycemic','Basic Metabolic','mg/dL','celf-v0.4'),
('lab','Fasting Blood Sugar','glucose_fasting','Fasting Glucose','glycemic','Basic Metabolic','mg/dL','celf-v0.4'),
('lab','FBS','glucose_fasting','Fasting Glucose','glycemic','Basic Metabolic','mg/dL','celf-v0.4'),
('lab','Cholesterol, Total','lipid_total_cholesterol','Total Cholesterol','lipids','Lipid Panel','mg/dL','celf-v0.4'),
('lab','HDL Cholesterol','lipid_hdl_c','HDL Cholesterol','lipids','Lipid Panel','mg/dL','celf-v0.4'),
('lab','LDL Cholesterol, Calc','lipid_ldl_c','LDL Cholesterol','lipids','Lipid Panel','mg/dL','celf-v0.4'),
('lab','LDL Cholesterol - Calculated','lipid_ldl_c','LDL Cholesterol','lipids','Lipid Panel','mg/dL','celf-v0.4'),
('lab','T3, Total','thyroid_t3_total','Total T3','thyroid','Thyroid Panel','ng/dL','celf-v0.4'),
('lab','T4, Total','thyroid_t4_total','Total T4','thyroid','Thyroid Panel','ug/dL','celf-v0.4'),
('lab','TSH, 3rd Gen','thyroid_tsh','TSH','thyroid','Thyroid Panel','uIU/mL','celf-v0.4'),
('lab','Vitamin B12','vitamin_b12','Vitamin B12','vitamins','Vitamin Panel','pg/mL','celf-v0.4'),
('lab','25-Hydroxy Vitamin D','vitamin_d_25oh','25-OH Vitamin D','vitamins','Vitamin Panel','ng/mL','celf-v0.4'),
('lab','C-Reactive Protein','inflammation_crp','CRP','inflammation','Inflammation','mg/L','celf-v0.4'),
('lab','High Sensitivity CRP','inflammation_hscrp','High-Sensitivity CRP','inflammation','Inflammation','mg/L','celf-v0.4'),
('lab','Homocysteine, Serum','metabolic_homocysteine','Homocysteine','metabolic','Cardiovascular Metabolic','umol/L','celf-v0.4'),
('inbody','segmental_ecw_tbw_right_leg','body_ecw_tbw_right_leg','Right Leg ECW/TBW','hydration','InBody 970','ratio','celf-v0.4'),
('inbody','segmental_ecw_tbw_left_leg','body_ecw_tbw_left_leg','Left Leg ECW/TBW','hydration','InBody 970','ratio','celf-v0.4'),
('inbody','segmental_ecw_tbw_right_arm','body_ecw_tbw_right_arm','Right Arm ECW/TBW','hydration','InBody 970','ratio','celf-v0.4'),
('inbody','segmental_ecw_tbw_left_arm','body_ecw_tbw_left_arm','Left Arm ECW/TBW','hydration','InBody 970','ratio','celf-v0.4'),
('inbody','segmental_ecw_tbw_trunk','body_ecw_tbw_trunk','Trunk ECW/TBW','hydration','InBody 970','ratio','celf-v0.4'),
('inbody','segmental_lean_right_arm','body_lean_right_arm','Right Arm Lean Mass','body_composition','InBody 970','lb','celf-v0.4'),
('inbody','segmental_lean_left_arm','body_lean_left_arm','Left Arm Lean Mass','body_composition','InBody 970','lb','celf-v0.4'),
('inbody','segmental_lean_right_leg','body_lean_right_leg','Right Leg Lean Mass','body_composition','InBody 970','lb','celf-v0.4'),
('inbody','segmental_lean_left_leg','body_lean_left_leg','Left Leg Lean Mass','body_composition','InBody 970','lb','celf-v0.4'),
('inbody','segmental_lean_trunk','body_lean_trunk','Trunk Lean Mass','body_composition','InBody 970','lb','celf-v0.4'),
('inbody','skeletal_muscle_mass','body_smm','Skeletal Muscle Mass','body_composition','InBody 970','lb','celf-v0.4'),
('inbody','body_fat_mass','body_fat_mass','Body Fat Mass','body_composition','InBody 970','lb','celf-v0.4'),
('inbody','fat_free_mass','body_fat_free_mass','Fat Free Mass','body_composition','InBody 970','lb','celf-v0.4'),
('inbody','dry_lean_mass','body_dry_lean_mass','Dry Lean Mass','body_composition','InBody 970','lb','celf-v0.4'),
('inbody','body_fat_percent','body_fat_pct','Percent Body Fat','body_composition','InBody 970','%','celf-v0.4'),
('inbody','visceral_fat_area','body_visceral_fat_area','Visceral Fat Area','body_composition','InBody 970','cm2','celf-v0.4'),
('inbody','basal_metabolic_rate','body_bmr','Basal Metabolic Rate','metabolic','InBody 970','kcal/day','celf-v0.4'),
('inbody','ecw_tbw_ratio','body_ecw_tbw','ECW/TBW Ratio','hydration','InBody 970','ratio','celf-v0.4'),
('inbody','phase_angle_whole_body','phase_angle_whole_body','Phase Angle (Whole Body)','cellular_integrity','InBody 970','degrees','celf-v0.4')
on conflict (source_system, reveal_canonical, map_version) do nothing;