#!/usr/bin/env python3
"""Patient Reveal — Azure migration operator tool (Gate G0/G1, handover §10.1).

Renders an Azure-portable schema baseline from the LIVE catalogue: enum types,
tables, constraints, indexes, routines, triggers, RLS enablement, policies and
grants — plus the compatibility prerequisites (roles, `auth.*` definer shims on a
non-owner role, minimal `storage` schema) that RLS policies depend on.

This is a schema/DDL renderer only. It never reads or writes patient rows, never
dumps data, and never contacts Azure. Data movement is a separate rehearsed step.

Transformations applied (each one is itemized in transformation-manifest.json):
  T1  auth.users foreign keys      -> app_identity.app_users(id)
  T2  auth.uid()/auth.jwt()/role() -> definer shims over request.jwt.claims,
                                      owned by a non-owner role (no RLS bypass)
  T3  platform-default `anon` table grants are NOT replayed; anon is granted only
      where a live policy actually names the anon role
  T4  storage.objects policies      -> emitted as advisory comments; Blob + SAS is
                                      the target file authority, not table policies

Usage:
  ops/migrate/render_azure_baseline.py <CATALOGUE_DIR> [OUTPUT_DIR]
"""

from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
from collections import defaultdict

HEADER = """-- GENERATED by ops/migrate/render_azure_baseline.py — do not hand-edit.
-- Source: live catalogue capture {cat_hash}
-- Target: Azure Database for PostgreSQL Flexible Server
"""


def psql(sql: str) -> list[str]:
    out = subprocess.run(
        ["psql", "-X", "-q", "-v", "ON_ERROR_STOP=1", "-tAc", sql],
        capture_output=True,
        text=True,
        check=True,
    )
    return [line for line in out.stdout.split("\n") if line.strip()]


def load(cat_dir: str, section: str):
    with open(os.path.join(cat_dir, f"{section}.json")) as fh:
        return json.load(fh)


def render_types() -> str:
    rows = psql(
        "select format('CREATE TYPE public.%I AS ENUM (%s);', t.typname, "
        "string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder)) "
        "from pg_type t join pg_enum e on e.enumtypid = t.oid "
        "join pg_namespace n on n.oid = t.typnamespace where n.nspname='public' "
        "group by t.typname order by t.typname"
    )
    return "\n".join(rows) + "\n"


def render_tables(columns, constraints) -> tuple[str, list[str]]:
    cols_by_table = defaultdict(list)
    for c in columns:
        if c["schema"] == "public":
            cols_by_table[c["table"]].append(c)

    cons_by_table = defaultdict(list)
    for c in constraints:
        if c["schema"] != "public":
            continue
        cons_by_table[c["table"].replace("public.", "")].append(c)

    auth_fk_rewrites: list[str] = []
    out: list[str] = []
    for table in sorted(cols_by_table):
        col_lines = []
        for c in sorted(cols_by_table[table], key=lambda r: r["ordinal"]):
            frag = f'  "{c["column"]}" {c["type"]}'
            if c["type"] in ("USER-DEFINED", "ARRAY"):
                # information_schema loses the concrete type name; ask the catalogue
                frag = "  " + psql(
                    "select format('%I %s', a.attname, format_type(a.atttypid, a.atttypmod)) "
                    f"from pg_attribute a where a.attrelid = 'public.{table}'::regclass "
                    f"and a.attname = {sql_lit(c['column'])}"
                )[0]
            if c["default"] is not None:
                frag += f' DEFAULT {c["default"]}'
            if c["nullable"] == "NO":
                frag += " NOT NULL"
            col_lines.append(frag)

        table_cons = []
        for con in sorted(cons_by_table.get(table, []), key=lambda r: r["name"]):
            if con["type"] == "t":  # trigger constraints are emitted with triggers
                continue
            definition = con["definition"]
            if "auth.users" in definition:
                definition = definition.replace(
                    "auth.users", "app_identity.app_users"
                )
                auth_fk_rewrites.append(f"{table}.{con['name']}")
            table_cons.append(f'  CONSTRAINT "{con["name"]}" {definition}')

        body = ",\n".join(col_lines + table_cons)
        out.append(f'CREATE TABLE public."{table}" (\n{body}\n);')
    return "\n\n".join(out) + "\n", auth_fk_rewrites


def sql_lit(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def render_indexes(indexes) -> str:
    lines = []
    for idx in indexes:
        if idx["schema"] != "public":
            continue
        # primary/unique constraints already emitted with the table
        if idx["name"].endswith("_pkey") or idx["definition"].startswith(
            "CREATE UNIQUE INDEX"
        ) and idx["name"].endswith("_key"):
            continue
        lines.append(idx["definition"] + ";")
    return "\n".join(lines) + "\n"


def render_routines() -> str:
    rows = psql(
        "select replace(pg_get_functiondef(p.oid), E'\\n', '\\u0001') "
        "from pg_proc p join pg_namespace n on n.oid = p.pronamespace "
        "where n.nspname='public' order by p.proname, pg_get_function_identity_arguments(p.oid)"
    )
    defs = [r.replace("\u0001", "\n") + ";" for r in rows]
    return "\n\n".join(defs) + "\n"


def render_triggers(triggers) -> str:
    return (
        "\n".join(t["definition"] + ";" for t in triggers if t["schema"] == "public")
        + "\n"
    )


def render_security(rls_enabled, policies, table_acls) -> tuple[str, dict]:
    lines: list[str] = []
    anon_kept: list[str] = []
    anon_dropped: list[str] = []
    storage_policies: list[str] = []

    anon_policy_tables = {
        p["table"]
        for p in policies
        if p["schema"] == "public" and p["roles"] and "anon" in p["roles"]
    }

    acl_by_table = {
        r["table"]: r["acl"] for r in table_acls if r["schema"] == "public"
    }

    for t in sorted(
        (r for r in rls_enabled if r["schema"] == "public"), key=lambda r: r["table"]
    ):
        if not t["rls_enabled"]:
            lines.append(
                f'-- REVIEW: public.{t["table"]} has RLS disabled in the live catalogue.'
            )
        table = t["table"]
        acl = acl_by_table.get(table, "")
        grants = []
        if "authenticated=" in acl:
            grants.append(
                f'GRANT SELECT, INSERT, UPDATE, DELETE ON public."{table}" TO authenticated;'
            )
        grants.append(f'GRANT ALL ON public."{table}" TO service_role;')
        if table in anon_policy_tables:
            grants.append(f'GRANT SELECT ON public."{table}" TO anon;')
            anon_kept.append(table)
        elif "anon=" in acl:
            anon_dropped.append(table)
        lines.extend(grants)
        lines.append(f'ALTER TABLE public."{table}" ENABLE ROW LEVEL SECURITY;')
        lines.append("")

    for p in sorted(
        policies, key=lambda r: (r["schema"], r["table"], r["policy"])
    ):
        roles = ", ".join(p["roles"] or []) or "public"
        clause = f'CREATE POLICY "{p["policy"]}" ON {p["schema"]}."{p["table"]}"'
        clause += f' AS {"PERMISSIVE" if p["permissive"] == "PERMISSIVE" else "RESTRICTIVE"}'
        clause += f' FOR {p["command"]} TO {roles}'
        if p["using"]:
            clause += f' USING ({p["using"]})'
        if p["check"]:
            clause += f' WITH CHECK ({p["check"]})'
        clause += ";"
        if p["schema"] == "storage":
            storage_policies.append("-- T4 (advisory, Blob+SAS is authoritative): " + clause)
        else:
            lines.append(clause)

    lines.append("")
    lines.append("-- storage.objects policies are not replayed as table policies:")
    lines.extend(storage_policies)

    return "\n".join(lines) + "\n", {
        "anon_grants_kept": sorted(anon_kept),
        "anon_grants_dropped": sorted(anon_dropped),
        "storage_policies_advisory": len(storage_policies),
    }


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__)
        return 2
    cat_dir = sys.argv[1]
    out_dir = sys.argv[2] if len(sys.argv) > 2 else os.path.join(cat_dir, "azure-baseline")
    os.makedirs(out_dir, exist_ok=True)

    with open(os.path.join(cat_dir, "catalogue-hash.txt")) as fh:
        cat_hash = fh.read().strip()

    columns = load(cat_dir, "columns")
    constraints = load(cat_dir, "constraints")
    indexes = load(cat_dir, "indexes")
    triggers = load(cat_dir, "triggers")
    rls_enabled = load(cat_dir, "rls_enabled")
    policies = load(cat_dir, "policies")
    table_acls = load(cat_dir, "table_acls")
    buckets = load(cat_dir, "storage_buckets")
    rollup = load(cat_dir, "storage_object_rollup")

    prereq_src = os.path.join(os.path.dirname(__file__), "azure-baseline-prereqs.sql")
    with open(prereq_src) as fh:
        prereqs = fh.read()

    tables_sql, auth_fks = render_tables(columns, constraints)
    security_sql, security_notes = render_security(rls_enabled, policies, table_acls)

    files = {
        "000_prereqs.sql": prereqs,
        "010_types.sql": render_types(),
        "020_tables.sql": tables_sql,
        "030_indexes.sql": render_indexes(indexes),
        "040_routines.sql": render_routines(),
        "050_triggers.sql": render_triggers(triggers),
        "060_security.sql": security_sql,
    }

    manifest = {
        "source_catalogue_hash": cat_hash,
        "transformations": {
            "T1_auth_users_fk_rewritten": sorted(auth_fks),
            "T2_auth_shims": [
                "auth.uid()",
                "auth.jwt()",
                "auth.role()",
                "owner: app_auth_owner (non-owner of application tables)",
            ],
            "T3_anon_grants": {
                "kept_because_policy_names_anon": security_notes["anon_grants_kept"],
                "dropped_platform_default": security_notes["anon_grants_dropped"],
            },
            "T4_storage_policies_advisory": security_notes[
                "storage_policies_advisory"
            ],
        },
        "storage": {"buckets": buckets, "object_rollup": rollup},
        "files": [],
    }

    for name, content in files.items():
        body = HEADER.format(cat_hash=cat_hash) + "\n" + content
        path = os.path.join(out_dir, name)
        with open(path, "w") as fh:
            fh.write(body)
        manifest["files"].append(
            {
                "file": name,
                "bytes": len(body.encode()),
                "sha256": hashlib.sha256(body.encode()).hexdigest(),
            }
        )

    baseline_hash = hashlib.sha256(
        "\n".join(f'{f["file"]}:{f["sha256"]}' for f in manifest["files"]).encode()
    ).hexdigest()
    manifest["baseline_hash"] = baseline_hash

    with open(os.path.join(out_dir, "transformation-manifest.json"), "w") as fh:
        json.dump(manifest, fh, indent=2)
        fh.write("\n")

    for f in manifest["files"]:
        print(f'{f["file"]:<20} {f["bytes"]:>8} bytes  {f["sha256"][:16]}')
    print()
    print(f"azure baseline: {out_dir}")
    print(f"baseline-hash:  {baseline_hash}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
